### ISSUE TITLE
Question about license.

### ISSUE THREAD

**Issue by ghost** [LelsersLasers/UnderwaterWorld#8]
That's really such an amazing project.
I was wondering about it's license, MIT, Apache 2, etc..
Or is it public domain or unlicense?
Please tell me or add LICENSE file to the repo and thanks again for this amazing project.

**Comment by LelsersLasers** [comment]
Thanks for letting me know! I just added an MIT License to the project.
If you want to learn more I highly recommend skimming through some of these links: [https://github.com/LelsersLasers/UnderwaterWorld?tab=readme-ov-file#resources](https://github.com/LelsersLasers/UnderwaterWorld?tab=readme-ov-file#resources)
